### ISSUE TITLE
Режим комментирования ломается после нажатия сначала скрыть комментарии, затем - показать комментарии

### ISSUE THREAD

**Issue by dustyo-O** [denver411/netology_js_in_browser_diploma#2]
При этом остается мертвая форма, но повзаимодействовать с ней, так и открыть новую форму уже нельзя

запись бажули:
https://monosnap.com/file/wntqLejUzwXOHe6mD2acXOeoILilPP

(кстати верстка формы выглядит немного поломанной)

**Comment by denver411** [comment]
Поправил
