### ISSUE TITLE
Мелкие ошибки и code style

### ISSUE THREAD

**Issue by dustyo-O** [denver411/netology_js_in_browser_diploma#4]
не нужно
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L149

лишняя пустая строка
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L154
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L297
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L315
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L389
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L400
вообще пустые строки ты вставляешь не там, где нужно, а где нужно - их нет

лишние скобки
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L155

нужна точка с запятой
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L254
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L272
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L285
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L296
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L339
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L364
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L379
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L397
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L622
ну и так далее, посмотри внимательно

кавычки вокруг строк должны быть либо одинарными, либо бектиками, там, где это нужно. По максимуму надо выпилить двойные кавычки
начиная с
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L14
 - и очень много еще мест

**Comment by dustyo-O** [comment]
название атрибутов не надо брать в кавычки без необходимости
https://github.com/denver411/netology_js_in_browser_diploma/blob/7943dfdca7950f4c8b0f52eefc71415b6eac13a0/js/solution.js#L34
и подобные места - их много

**Comment by denver411** [comment]
Исправил.

> вообще пустые строки ты вставляешь не там, где нужно, а где нужно - их нет

По этому поводу где лучше почитать?

**Comment by dustyo-O** [comment]
Принято вставлять пустые строки после объявления переменных и перед return. Также, можно отбивать одной пустой строкой какой-то самодостаточный блок кода
